name: Build & deploy to GitHub Pages

on:
  push:
    branches:
      - master
  workflow_dispatch:

permissions:
  contents: read
  pages: write      # to deploy to Pages
  id-token: write   # to verify the deployment originates from an appropriate source
  packages: read    # to access idn-lib GitHub NPM package

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20 # sass breaks with node v21
          cache: npm
          registry-url: "https://npm.pkg.github.com"
      - name: Install and build
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VITE_AGENT_NAMED_GRAPH: ${{ secrets.VITE_AGENT_NAMED_GRAPH }}
          VITE_TRIPLESTORE_URL: ${{ secrets.VITE_TRIPLESTORE_URL }}
          VITE_BASE_URL: /idn-metadata-creator/
        run: |
          npm ci
          CI=false npm run build
          cp dist/index.html dist/404.html
      - name: Setup Pages
        uses: actions/configure-pages@v4
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'dist'
  deploy:
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
