name: Publish Docker image and deploy

on:
  push:
    branches:
      - main
  repository_dispatch:
    types: [trigger-workflow]
  workflow_dispatch:

permissions:
  contents: read
  id-token: write
  packages: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ghcr.io/idn-au/met:latest
          secrets: |
            "npm_token=${{ secrets.GITHUB_TOKEN }}"
  deploy:
    needs: publish
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v4
    - name: Stop current met if exists
      env: 
        FUSEKI_URL: ${{ secrets.FUSEKI_URL }}
        FUSEKI_USERNAME: ${{ secrets.FUSEKI_USERNAME }}
        FUSEKI_PASSWORD: ${{ secrets.FUSEKI_PASSWORD }}
      run: |
        if [ -d "/home/ubuntu/met/" ]; then
          cd /home/ubuntu/met/
          docker compose -f met-compose.yaml stop met
        fi
    - name: Copy files
      run: |
        mkdir -p /home/ubuntu/met/
        cp -Rf met-compose.yaml /home/ubuntu/met/
    - name: Deploy met
      working-directory: /home/ubuntu/met/
      env: 
        FUSEKI_URL: ${{ secrets.FUSEKI_URL }}
        FUSEKI_USERNAME: ${{ secrets.FUSEKI_USERNAME }}
        FUSEKI_PASSWORD: ${{ secrets.FUSEKI_PASSWORD }}
      run: docker compose -f met-compose.yaml up -d
